services:
  todo-app:
    container_name: todo-app
    build: .
    working_dir: /home/app
    ports:
      - "8765:8765"
      - "2345:2345"
    volumes:
      - type: bind
        source: .
        target: /home/app
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo
      DB_HOST: mysql
      JWT_SECRET: jwt_secret
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      APP_URL: "http://localhost:8765"
      # These will be loaded from the .env file
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: "http://localhost:8765/auth/google/callback"
    depends_on:
      - mysql
      - mailpit
    command: ["air"]

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - mailpit_data:/data

  web:
    build: ./web
    container_name: todo-web
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - todo-app

volumes:
  mysql_data:
  mailpit_data:
