networks:
  todo-network:
    external: true

services:
  todo-app:
    container_name: todo-app
    build: .
    working_dir: /home/app
    ports:
      - "8765:8765"
      - "2345:2345"
    volumes:
      - type: bind
        source: .
        target: /home/app
    networks:
      - todo-network
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo
      DB_HOST: mysql
      JWT_SECRET: jwt_secret
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      APP_URL: "http://local.todo.com"
      # These will be loaded from the .env file
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: "http://local.todo.com/auth/google/callback"
    command: ["air"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.monolith.rule=Host(`local.todo.com`) && (PathPrefix(`/auth`) || PathPrefix(`/user`) || PathPrefix(`/todos`))
      - traefik.http.routers.monolith.entrypoints=web
      - traefik.http.services.monolith.loadbalancer.server.port=8765
      - traefik.http.routers.monolith.service=monolith
